### ISSUE TITLE
No background/overlay color for highlighted characters

### ISSUE THREAD

**Issue by HerrimanCoder** [CharlieEtienne/material-vcl#3]
I love the Material Theme (dark) in HeidiSQL 10.1 - except when I highlight a line, there is no background color behind/over the highlighted characters. When highlighted, it does however turn all the text white, so you can kind of tell it's highlighted, but it's very hard to tell. I want the highlighted text to remain the same color, but some kind of highlight/overlay color to easily show what is highlighted. Is there some way I can solve this?

In Heidi, you can scarcely tell what is highlighted:
![highlight1](https://user-images.githubusercontent.com/8998614/56296640-2624b900-60ec-11e9-9896-9e53fa6c4f8c.png)

In NPP by contrast, you can easily tell what is highlighted:
![highlight2](https://user-images.githubusercontent.com/8998614/56296674-36d52f00-60ec-11e9-90a8-2831c7d161ec.png)

I have been in Heidi->Tools->Preferences->SQL and tried many things, but nothing works.

What can be done?

**Comment by CharlieEtienne** [comment]
Hi @HerrimanCoder, thanks for your message. It seems weird because I thought this issue was fixed  in Material Theme 1.2...

Just to be sure, can you confirm it is the same issue as here : https://github.com/CharlieEtienne/material-vcl/issues/2 ?

If it is, I think it has been fixed in a previous release on HeidiSql. Maybe in a nightly build... Is your HeidiSQL up to date ?

**Comment by HerrimanCoder** [comment]
I updated HeidiSQL and it is fixed now. Thank you.

**Comment by ansgarbecker** [comment]
Oh, this reminds me the v10.1 release still has the unfixed theme. It's time for a new release.
